name: Test

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - rust/**
      - test/**
      - scripts/run-tests.js
      - scripts/build-rust-wasm.js
      - build/**
      - dist/**
      - .cargo/**
      - .github/workflows/test.yaml
      - esbuild.config.js
      - package.json
      - package-lock.json
      - tsconfig.json
      - ARCHITECTURE.md

  pull_request:
    branches:
      - main
    paths:
      - src/**
      - rust/**
      - test/**
      - scripts/run-tests.js
      - scripts/build-rust-wasm.js
      - build/**
      - dist/**
      - .cargo/**
      - .github/workflows/test.yaml
      - esbuild.config.js
      - package.json
      - package-lock.json
      - tsconfig.json
      - ARCHITECTURE.md

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows 11
            os: windows-2025
          - name: MacOS 15
            os: macos-15-intel
          - name: Ubuntu 24
            os: ubuntu-24.04

    steps:
      -
        name: Checkout
        uses: actions/checkout@v7

      -
        name: Set up Node
        uses: actions/setup-node@v7
        with:
          node-version: "24"

      -
        name: Install dependencies
        run: npm ci

      -
        name: Install Rust tooling
        run: |
          rustup target add wasm32-unknown-unknown
          rustup component add rustfmt

      -
        name: Check Rust formatting
        run: cargo fmt --manifest-path ./rust/Cargo.toml -- --check

      -
        name: Run Rust tests
        run: npm run test:rs

      -
        name: Install Vulkan driver
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y mesa-vulkan-drivers vulkan-tools
          vulkaninfo --summary

      -
        name: Build
        run: npm run build

      -
        name: Run Node tests
        run: npm run test:js
