name: Test

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - rust/**
      - test/**
      - scripts/run-tests.js
      - scripts/build-rust-wasm.js
      - build/**
      - dist/**
      - .cargo/**
      - .github/workflows/test.yaml
      - esbuild.config.js
      - playwright.config.js
      - package.json
      - package-lock.json
      - tsconfig.json
      - ARCHITECTURE.md

  pull_request:
    branches:
      - main
    paths:
      - src/**
      - rust/**
      - test/**
      - scripts/run-tests.js
      - scripts/build-rust-wasm.js
      - build/**
      - dist/**
      - .cargo/**
      - .github/workflows/test.yaml
      - esbuild.config.js
      - playwright.config.js
      - package.json
      - package-lock.json
      - tsconfig.json
      - ARCHITECTURE.md

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows 11
            os: windows-2025
          - name: MacOS 15
            os: macos-15-intel
          - name: Ubuntu 24
            os: ubuntu-24.04

    steps:
      -
        name: Checkout
        uses: actions/checkout@v7

      -
        name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 24

      -
        name: Install Node dependencies
        run: npm ci

      -
        name: Install Playwright dependencies
        if: ${{ runner.os == 'Linux' }}
        run: npx playwright install-deps chromium

      -
        name: Install Chromium
        run: npx playwright install --no-shell chromium

      -
        name: Install Rust dependencies
        run: |
          rustup target add wasm32-unknown-unknown
          rustup component add rustfmt

      -
        name: Run Rust tests
        run: |
          cargo fmt --manifest-path ./rust/Cargo.toml -- --check
          npm run test:rs

      -
        name: Build WasmGPU
        run: npm run build

      -
        name: Run Node tests
        run: npm run test:js

      -
        name: Upload results
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v7
        with:
          name: playwright-report-${{ matrix.os }}
          path: playwright-report/
          retention-days: 7
